# A.I. Apex Brain - Monitoring Configuration
# Comprehensive monitoring and alerting setup

apiVersion: v1
kind: ConfigMap
metadata:
  name: apex-brain-monitoring-config
  namespace: apex-brain
data:
  monitoring.yaml: |
    # Prometheus Configuration
    prometheus:
      enabled: true
      retention: "30d"
      scrape_interval: "15s"
      evaluation_interval: "15s"
      external_labels:
        cluster: "apex-brain"

    # Grafana Configuration
    grafana:
      enabled: true
      admin_password: "generate_secure_password"
      dashboards:
        - name: "System Overview"
          file: "system-overview.json"
        - name: "Algorithm Performance"
          file: "algorithm-performance.json"
        - name: "Model Metrics"
          file: "model-metrics.json"
        - name: "Voice Analytics"
          file: "voice-analytics.json"

    # Alerting Rules
    alerts:
      - name: "HighCPUUsage"
        condition: "cpu_usage > 80"
        duration: "5m"
        severity: "warning"
        message: "High CPU usage detected"

      - name: "HighMemoryUsage"
        condition: "memory_usage > 85"
        duration: "3m"
        severity: "warning"
        message: "High memory usage detected"

      - name: "PodCrashLooping"
        condition: "pod_restarts > 3"
        duration: "1m"
        severity: "critical"
        message: "Pod is crash looping"

      - name: "ServiceDown"
        condition: "service_availability < 1"
        duration: "1m"
        severity: "critical"
        message: "Service is down"

    # Notification Channels
    notifications:
      email:
        enabled: true
        smtp_server: "smtp.gmail.com"
        smtp_port: 587
        recipients: ["admin@company.com"]

      slack:
        enabled: false
        webhook_url: "https://hooks.slack.com/services/..."
        channel: "#alerts"

      webhook:
        enabled: false
        url: "https://your-webhook-endpoint.com/alerts"

    # Log Management
    logging:
      level: "info"
      retention: "30d"
      rotation: "daily"
      aggregation: true

    # Custom Metrics
    custom_metrics:
      - name: "algorithm_execution_time"
        type: "histogram"
        help: "Time taken to execute algorithms"

      - name: "model_inference_requests"
        type: "counter"
        help: "Number of model inference requests"

      - name: "voice_synthesis_quality"
        type: "gauge"
        help: "Voice synthesis quality score"
