# A.I. Apex Brain - Production Configuration
# Suitable for: Large teams, enterprise deployments

apiVersion: v1
kind: ConfigMap
metadata:
  name: apex-brain-production-config
  namespace: apex-brain
data:
  system.yaml: |
    deployment:
      mode: "production"
      environment: "production"
      high_availability: true
      disaster_recovery: true

    infrastructure:
      server_type: "cx51"        # 8 vCPU, 32GB RAM
      storage_size: "160GB"
      region: "ash"
      backup_region: "hel"      # Helsinki backup
      auto_scaling: true
      max_replicas: 10
      load_balancer: true

    # Full Algorithm Framework
    algorithms:
      lazy_loading: true
      cascade_depth: 5           # Maximum depth
      quantum_enhancement: true
      exponential_enhancement: true
      recursive_optimization: true
      all_algorithms_available: true

    # Production Resources
    resources:
      postgresql:
        memory_limit: "8Gi"
        cpu_limit: "4000m"
        storage: "100Gi"
        backup_enabled: true
        replication: true
        connection_pooling: true
      redis:
        memory_limit: "4Gi"
        cpu_limit: "2000m"
        persistence: true
        clustering: true
      llm_engine:
        memory_limit: "16Gi"
        cpu_limit: "8000m"
        model: "meta-llama/Meta-Llama-3.1-8B-Instruct"
        quantization: "4bit"
        replicas: 3
        gpu_enabled: false        # CPU optimization for cost
      algorithmic_engine:
        memory_limit: "8Gi"
        cpu_limit: "4000m"
        replicas: 3
        parallel_processing: true

    # Enterprise Voice Features
    voice:
      enabled: true
      enterprise_voices: true
      custom_voice_training: true
      multi_language_support: true
      real_time_translation: true
      voice_analytics: true

    # Enterprise Monitoring
    monitoring:
      prometheus: true
      grafana: true
      alertmanager: true
      jaeger_tracing: true
      log_aggregation: true
      sla_monitoring: true
      performance_analytics: true

    # Enterprise Security
    security:
      oauth2_integration: true
      rbac_enabled: true
      audit_logging: true
      compliance_reporting: true
      encryption_at_rest: true
      network_policies: true

    # Enterprise Automation
    automation:
      ci_cd_integration: true
      auto_deployment: true
      canary_releases: true
      rollback_automation: true
      capacity_planning: true
